<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ST558_Homework5_Haverhals</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d0cfe7a3482e0d49a74229a8f3b76718.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ST558_Homework5_Haverhals</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="task-1---querying-an-api-and-a-tidy-style-function" class="level1">
<h1><strong>Task 1 - Querying an API and a Tidy-Style Function</strong></h1>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section">1.</h2>
<p>To get started, I wanted to put my API key somewhere handy.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># API key: 020bec21c3dd48a4b5485d44cbffd92f</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now, I’ll make my request to API to see if I can find information related to recent political polls.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(httr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>poll_info<span class="ot">&lt;-</span><span class="fu">GET</span>(<span class="st">"https://newsapi.org/v2/everything?q=polls&amp;from=2026-08-20&amp;language=en&amp;pageSize=50&amp;apiKey=020bec21c3dd48a4b5485d44cbffd92f"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1">2.</h2>
<p>Next, we’re asked to parse what we just received:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jsonlite)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'jsonlite' was built under R version 4.5.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>parsed <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">rawToChar</span>(poll_info<span class="sc">$</span>content))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Total results="</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Total results="</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>parsed[[<span class="dv">2</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5007</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(parsed[[<span class="dv">3</span>]],<span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  source.id source.name                           author
1      &lt;NA&gt; Gizmodo.com                     Ece Yildirim
2  bbc-news    BBC News https://www.facebook.com/bbcnews
3  bbc-news    BBC News https://www.facebook.com/bbcnews
4  bbc-news    BBC News https://www.facebook.com/bbcnews
5      &lt;NA&gt;         NPR             The Associated Press
                                                                        title
1     TikTok Is Supercharging Comments With Voice, Photo Carousels, and Polls
2                  Close race in Sweden as hard right eyes role in government
3              German far-right set for big win in eastern state - exit polls
4   The Papers: 'Military jet tripped chaos' and 'A failure for dying people'
5 German exit polls suggest far-right party has big lead in regional election
                                                                                                                                                                                             description
1                                                                                              So much of TikTok lives in the comment section, the company is basically building a site within its site.
2                                                        Prime Minister Ulf Kristersson has promised cabinet jobs for the Sweden Democrats, but the rival left-wing bloc has a narrow lead in the polls.
3                                                                    Germany's AfD has hailed a "historic result" and is projected to win 44.5% of the vote, far ahead of the conservative CDU on 18.5%.
4                                                                                               Several of the papers consider on the fall of the assisted dying bill in the House of Commons on Friday.
5 The Alternative for Germany party has a strong lead in a regional election, but it is unclear if it will be able to form Germany's's first far-right state government since WWII, exit polls indicate.
                                                                                                                   url
1                 https://gizmodo.com/tiktok-is-supercharging-comments-with-voice-photo-carousels-and-polls-2000806865
2                                                                     https://www.bbc.co.uk/news/articles/cwyz8dn5nn3o
3                                                                     https://www.bbc.co.uk/news/articles/cy4zejgz3z9o
4                                                                     https://www.bbc.co.uk/news/articles/c0qx7q25d9xo
5 https://www.npr.org/2026/09/06/nx-s1-5955677/german-exit-polls-suggest-far-right-party-big-lead-in-regional-election
                                                                                                                                                                                                                         urlToImage
1                                                                                                                                                          https://gizmodo.com/app/uploads/2026/07/Best-VPN-for-TikTok-1200x675.jpg
2                                                                                                                       https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/3cfc/live/fe574770-add8-11f1-bc1f-3f186ca4140c.png
3                                                                                                                       https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/1a2d/live/537ff930-6139-11ee-b101-6f93d6dfbcc2.png
4                                                                                                                       https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/0608/live/eb82adc0-ae2c-11f1-933b-b9c22df145d4.png
5 https://npr.brightspotcdn.com/dims3/default/strip/false/crop/3376x1899+0+176/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F87%2F2b%2F18c9cb3346b3b36ea5ce83575239%2Fap26249325207672.jpg
           publishedAt
1 2026-09-03T18:55:05Z
2 2026-09-12T00:56:47Z
3 2026-09-06T16:10:46Z
4 2026-09-12T00:52:08Z
5 2026-09-06T16:36:48Z
                                                                                                                                                                                                                   content
1 TikTok just announced a major revamp of one of the platform’s most frequently used features: the comment section. TikTok users will now be able to share 60-second voice notes and polls as comments.\r\n… [+2504 chars]
2   Sweden's left- and right wing political blocs are in a tight race in Sunday's general election, with current conservative Prime Minister Ulf Kristersson promising cabinet jobs for hard-right allies i… [+1428 chars]
3    Germany's AfD is heading for a big victory in the eastern state of Saxony-Anhalt, far ahead of its mainstream arrivals, exit polls say. It is not yet clear if that would be enough to take power in th… [+955 chars]
4    Image caption, Reform UK has received a record £36m donation, the Telegraph reports. It writes that the donation, which was from cryptocurrency billionaire Ben Delo, is a "game-changing gift" for the… [+275 chars]
5   MAGDEBURG, Germany The Alternative for Germany party has a strong lead in a regional election, but it is unclear whether it will be able to form the country's first far-right state government since W… [+1950 chars]</code></pre>
</div>
</div>
<p>Here, we can see the list mentioned in the “R console” picture that shows that the status is “OK”, 4,962 articles were returned from the search and that the third item in the list is the (49x8) data frame.</p>
</section>
<section id="section-2" class="level2">
<h2 class="anchored" data-anchor-id="section-2">3.</h2>
<p>Now, to write a function to query the API. Note that I got help from Google on how to allow spaces in the x character string.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>search<span class="ot">&lt;-</span><span class="cf">function</span>(x,y,z){</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">URLencode</span>(<span class="fu">as.character</span>(x))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  url<span class="ot">&lt;-</span><span class="fu">paste0</span>(<span class="st">"https://newsapi.org/v2/everything?q="</span>,<span class="fu">as.character</span>(x),<span class="st">"&amp;from="</span>,<span class="fu">as.character</span>(y),<span class="st">"&amp;language=en&amp;pageSize=50&amp;apiKey="</span>,<span class="fu">as.character</span>(z))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  search_results<span class="ot">&lt;-</span><span class="fu">GET</span>(url)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  search_parsed <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">rawToChar</span>(search_results<span class="sc">$</span>content))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>search_parsed</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now, to try it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>search_1<span class="ot">&lt;-</span><span class="fu">search</span>(<span class="st">"polls"</span>,<span class="st">"2026-08-20"</span>,<span class="st">"020bec21c3dd48a4b5485d44cbffd92f"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Total results"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Total results"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>search_1[[<span class="dv">2</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5007</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(search_1[[<span class="dv">3</span>]],<span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  source.id source.name                           author
1      &lt;NA&gt; Gizmodo.com                     Ece Yildirim
2  bbc-news    BBC News https://www.facebook.com/bbcnews
3  bbc-news    BBC News https://www.facebook.com/bbcnews
4  bbc-news    BBC News https://www.facebook.com/bbcnews
5      &lt;NA&gt;         NPR             The Associated Press
                                                                        title
1     TikTok Is Supercharging Comments With Voice, Photo Carousels, and Polls
2                  Close race in Sweden as hard right eyes role in government
3              German far-right set for big win in eastern state - exit polls
4   The Papers: 'Military jet tripped chaos' and 'A failure for dying people'
5 German exit polls suggest far-right party has big lead in regional election
                                                                                                                                                                                             description
1                                                                                              So much of TikTok lives in the comment section, the company is basically building a site within its site.
2                                                        Prime Minister Ulf Kristersson has promised cabinet jobs for the Sweden Democrats, but the rival left-wing bloc has a narrow lead in the polls.
3                                                                    Germany's AfD has hailed a "historic result" and is projected to win 44.5% of the vote, far ahead of the conservative CDU on 18.5%.
4                                                                                               Several of the papers consider on the fall of the assisted dying bill in the House of Commons on Friday.
5 The Alternative for Germany party has a strong lead in a regional election, but it is unclear if it will be able to form Germany's's first far-right state government since WWII, exit polls indicate.
                                                                                                                   url
1                 https://gizmodo.com/tiktok-is-supercharging-comments-with-voice-photo-carousels-and-polls-2000806865
2                                                                     https://www.bbc.co.uk/news/articles/cwyz8dn5nn3o
3                                                                     https://www.bbc.co.uk/news/articles/cy4zejgz3z9o
4                                                                     https://www.bbc.co.uk/news/articles/c0qx7q25d9xo
5 https://www.npr.org/2026/09/06/nx-s1-5955677/german-exit-polls-suggest-far-right-party-big-lead-in-regional-election
                                                                                                                                                                                                                         urlToImage
1                                                                                                                                                          https://gizmodo.com/app/uploads/2026/07/Best-VPN-for-TikTok-1200x675.jpg
2                                                                                                                       https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/3cfc/live/fe574770-add8-11f1-bc1f-3f186ca4140c.png
3                                                                                                                       https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/1a2d/live/537ff930-6139-11ee-b101-6f93d6dfbcc2.png
4                                                                                                                       https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/0608/live/eb82adc0-ae2c-11f1-933b-b9c22df145d4.png
5 https://npr.brightspotcdn.com/dims3/default/strip/false/crop/3376x1899+0+176/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F87%2F2b%2F18c9cb3346b3b36ea5ce83575239%2Fap26249325207672.jpg
           publishedAt
1 2026-09-03T18:55:05Z
2 2026-09-12T00:56:47Z
3 2026-09-06T16:10:46Z
4 2026-09-12T00:52:08Z
5 2026-09-06T16:36:48Z
                                                                                                                                                                                                                   content
1 TikTok just announced a major revamp of one of the platform’s most frequently used features: the comment section. TikTok users will now be able to share 60-second voice notes and polls as comments.\r\n… [+2504 chars]
2   Sweden's left- and right wing political blocs are in a tight race in Sunday's general election, with current conservative Prime Minister Ulf Kristersson promising cabinet jobs for hard-right allies i… [+1428 chars]
3    Germany's AfD is heading for a big victory in the eastern state of Saxony-Anhalt, far ahead of its mainstream arrivals, exit polls say. It is not yet clear if that would be enough to take power in th… [+955 chars]
4    Image caption, Reform UK has received a record £36m donation, the Telegraph reports. It writes that the donation, which was from cryptocurrency billionaire Ben Delo, is a "game-changing gift" for the… [+275 chars]
5   MAGDEBURG, Germany The Alternative for Germany party has a strong lead in a regional election, but it is unclear whether it will be able to form the country's first far-right state government since W… [+1950 chars]</code></pre>
</div>
</div>
<p>So, it looks like a few more articles have been published between when I queried directly when I got the function working. Let’s try a few more times:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>search_2<span class="ot">&lt;-</span><span class="fu">search</span>(<span class="st">"Dolly Parton"</span>,<span class="st">"2026-08-20"</span>,<span class="st">"020bec21c3dd48a4b5485d44cbffd92f"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Total results"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Total results"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>search_2[[<span class="dv">2</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3988</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(search_2[[<span class="dv">3</span>]],<span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  source.id source.name                           author
1      &lt;NA&gt; Gizmodo.com                       Matt Novak
2  bbc-news    BBC News                             &lt;NA&gt;
3  bbc-news    BBC News https://www.facebook.com/bbcnews
4  bbc-news    BBC News                             &lt;NA&gt;
5  bbc-news    BBC News https://www.facebook.com/bbcnews
                                                                              title
1 Dolly Parton’s Sister Asks People to Stop Posting AI Slop of the Legendary Singer
2                              Dolly Parton: The life of a legendary country singer
3                                      The Papers: 'We will always love you, Dolly'
4                                       Watch Nashville fans lay flowers in tribute
5                          Dolly Parton: The country legend who sang from the heart
                                                                                                     description
1            "I hope nobody can ever replicate me or what I do. AI is a scary thing," said Dolly Parton in 2023.
2      Iconic country musician Dolly Parton has died at the age of 80, her family announced on her social media.
3     The death of country music legend and philanthropist Dolly Parton at aged 80 dominates Wednesday's papers.
4 The BBC's Helena Humphrey is outside the Country Music Hall of Fame where fans gathered to mourn Dolly Parton.
5     The singer, songwriter and actress is known for timeless hits including Jolene and I Will Always Love You.
                                                                                                                 url
1 https://gizmodo.com/dolly-partons-sister-asks-people-to-stop-posting-ai-garbage-of-the-legendary-singer-2000808660
2                                                                     https://www.bbc.co.uk/news/videos/c7831ld8e73o
3                                                                   https://www.bbc.co.uk/news/articles/c1wxnn50yero
4                                                                     https://www.bbc.co.uk/news/videos/cx2zm89zd99o
5                                                                   https://www.bbc.co.uk/news/articles/cz9xdl4g25zo
                                                                                                   urlToImage
1                                      https://gizmodo.com/app/uploads/2026/09/dolly-parton-1992-1200x675.jpg
2 https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/5cb3/live/731513a0-a0b2-11f1-aed2-8d6da8d75094.jpg
3 https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/70b9/live/a06e53b0-a0d1-11f1-a291-b542ee92de7c.jpg
4 https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/b497/live/4599c0a0-a117-11f1-a291-b542ee92de7c.jpg
5 https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/9edd/live/72b74780-4963-11f1-a87a-55dfd3c7a311.jpg
           publishedAt
1 2026-09-08T18:45:26Z
2 2026-08-25T18:27:22Z
3 2026-08-25T22:35:45Z
4 2026-08-26T06:37:30Z
5 2026-08-25T18:14:13Z
                                                                                                                                                                                                                   content
1   The internet was flooded with countless tributes to Dolly Parton after her death on Aug. 25 at the age of 80 years old. But some of the images, videos, and songs that have been distributed online are… [+4790 chars]
2     Iconic country musician Dolly Parton has died at the age of 80, her family announced on her social media. "Sadness lies with us, not with Dolly," Parton's nephew Brian Seaver said in a video announce… [+79 chars]
3    Image caption, The Guardian features Parton in her own words, saying: "I always wanted to be a star. I just seemed natural to me." Elsewhere, the paper's other top story says Prime Minister Andy Burn… [+162 chars]
4     The BBC's Helena Humphrey visited the Country Music Hall of Fame in Nashville, Tennessee, on Tuesday evening as fans gathered to mourn Dolly Parton. The country music star died at the age 80 after a … [+75 chars]
5 Despite being unable to read sheet music, Parton played several instruments including the banjo, harp, piano and saxophone.\r\nShe had her first number one hit - and first Grammy nomination - with the … [+1194 chars]</code></pre>
</div>
</div>
<p>And</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>search_3<span class="ot">&lt;-</span><span class="fu">search</span>(<span class="st">"Kyler Murray"</span>,<span class="st">"2026-08-20"</span>,<span class="st">"020bec21c3dd48a4b5485d44cbffd92f"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Total results"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Total results"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>search_3[[<span class="dv">2</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1125</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(search_3[[<span class="dv">3</span>]],<span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   source.id    source.name            author
1   bbc-news       BBC News       Ben Collins
2 fox-sports     Fox Sports              &lt;NA&gt;
3       &lt;NA&gt; Daily Norseman Christopher Gates
4       &lt;NA&gt;      New Atlas        Mike McRae
5       &lt;NA&gt;  NBCSports.com     Myles Simmons
                                                              title
1             Bears, Bills and Ravens win on record-breaking Sunday
2 Kyler Murray Departs First Vikings Start After Taking Hit To head
3                              Kyler Murray Injured Against Packers
4        Nearly all NFL players may die with a chronic brain injury
5                            Kyler Murray ruled out with concussion
                                                                                                                                                                                                                                                           description
1                                                                                                                                After kicking off the NFL season with a Super Bowl rematch and a trip to Australia, week one continued with a record-breaking Sunday.
2                                                                                                                                                                          Kyler Murray's debut with the Minnesota Vikings might have come to an abrupt end on Sunday.
3                                                                                                                                                                                                                                                  It didn’t look good
4 It’s NFL season again. In the Minnesota Vikings’ first game of the season, quarterback Kyler Murray’s debut run made it just 11 plays before a violent shoulder to the right side of his helmet sent him to the turf.Continue ReadingCategory: Alzheimer's &amp; Dement…
5                                                                                                                                                                           Murray sustained a hard blow to the head while sliding on a scramble in the first quarter.
                                                                                                   url
1                                  https://www.bbc.co.uk/sport/american-football/articles/c86x5pq12e6o
2                   https://www.foxsports.com/stories/nfl/kyler-murray-hit-head-vikings-injury-updates
3      https://www.dailynorseman.com/minnesota-vikings-news/99025/kyler-murray-injured-against-packers
4                     https://newatlas.com/brain/alzheimers-dementia/nfl-players-chronic-brain-injury/
5 https://www.nbcsports.com/nfl/profootballtalk/rumor-mill/news/kyler-murray-ruled-out-with-concussion
                                                                                                                                                                                                                                                                              urlToImage
1                                                                                                                                                                           https://ichef.bbci.co.uk/ace/branded_sport/1200/cpsprodpb/8c18/live/086f5950-afe6-11f1-a540-61c3f7fc4e6c.png
2                                                                                                                                                          https://a57.foxsports.com/statics.foxsports.com/www.foxsports.com/content/uploads/2026/09/1294/728/kyler-murray.jpg?ve=1&amp;tl=1
3                https://s.yimg.com/lo/mysterio/api/f9a7eff60deee69a48424632eff43ed63b7950378c0e214b1aedd2f7b76656ec/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_webp/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fsb_nation_articles_115%2Fed8d96222df16b9c79ac0711cff5a212.jpg
4 https://assets.newatlas.com/dims4/default/1ab2870/2147483647/strip/true/crop/2000x1050+0+100/resize/1200x630!/quality/90/?url=https%3A%2F%2Fnewatlas-brightspot.s3.ap-southeast-2.amazonaws.com%2F85%2Fc6%2Faf75cf73489fb8b14a7d272eac65%2Fnfl-concussions.jpg&amp;na.image_optimisation=0
5 https://nbcsports.brightspotcdn.com/dims4/default/d5a6b67/2147483647/strip/true/crop/5704x3209+0+103/resize/1440x810!/quality/90/?url=https%3A%2F%2Fnbc-sports-production-nbc-sports.s3.us-east-1.amazonaws.com%2Fbrightspot%2F01%2Fb8%2Fd4e538d14ae4bc3f1a3334db652b%2F2295108498.jpg
           publishedAt
1 2026-09-14T05:36:07Z
2 2026-09-13T21:08:45Z
3 2026-09-13T21:05:34Z
4 2026-09-15T14:35:02Z
5 2026-09-13T21:22:00Z
                                                                                                                                                                                                                    content
1   The Arizona Cardinals have been tipped by many to finish with the NFL's worst record, while the Los Angeles Chargers are seen as play-off contenders.\r\nBut the Chargers were humbled on their own turf … [+916 chars]
2   Kyler Murray's debut with the Minnesota Vikings came to an abrupt end on Sunday.\r\nThe Vikings quarterback exited in the middle stages of the first quarter of Sunday's game against the Green Bay Packe… [+799 chars]
3    The 2026 season opener didn't get off to a great start for the Minnesota Vikings, and it didn't get much better midway through the first quarter with a very scary moment involving the Vikings' starti… [+1111 chars]
4    Its NFL season again. In the Minnesota Vikings first game of the season, quarterback Kyler Murrays debut run made it just 11 plays before a violent shoulder to the right side of his helmet sent him t… [+3877 chars]
5 Kyler Murray will not return to Sundays season opener. \r\nThe Vikings announced Murray has been downgraded to out with a concussion.\r\nMurray sustained a hard, illegal blow to the head midway through t… [+539 chars]</code></pre>
</div>
</div>
</section>
</section>
<section id="task-2---summarizing-roller-coaster-data" class="level1">
<h1><strong>Task 2 - Summarizing Roller Coaster Data</strong></h1>
</section>
<section id="basic-eda" class="level1">
<h1>Basic EDA</h1>
<p>To begin this task, I went to the url provided and downloaded the file to our working directory. Because I haven’t yet, I’ll next load the tidyverse and readr packages.</p>
<p>Now, we’ll pull the data into R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>raw_coasters<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"data/635USrollercoasters.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 635 Columns: 21
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (12): Coaster, Park, City, State, Census Region, AgeGroup, Scale, Type, ...
dbl  (9): Year Opened, TopSpeed, MaxHeight, Drop, Length, Duration, # of Inv...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(raw_coasters)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [635 × 21] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Coaster        : chr [1:635] "Adrenaline Peak" "Adventure Express" "Afterburn" "Aftershock" ...
 $ Park           : chr [1:635] "Oaks Amusement Park" "Kings Island" "Carowinds" "Silverwood Theme Park" ...
 $ City           : chr [1:635] "Portland" "Mason" "Charlotte" "Athol" ...
 $ State          : chr [1:635] "Oregon" "Ohio" "North Carolina" "Idaho" ...
 $ Census Region  : chr [1:635] "West" "Midwest" "South" "West" ...
 $ Year Opened    : num [1:635] 2018 1991 1999 2008 2010 ...
 $ AgeGroup       : chr [1:635] "3:Newest" "2:Recent" "2:Recent" "3:Newest" ...
 $ TopSpeed       : num [1:635] 45 35 62 65.6 22 67 35 66 48 50 ...
 $ MaxHeight      : num [1:635] 72 63 113 192 25 ...
 $ Scale          : chr [1:635] "Extreme" "Thrill" "Extreme" "Extreme" ...
 $ Type           : chr [1:635] "Steel" "Steel" "Steel" "Steel" ...
 $ Design         : chr [1:635] "Sit Down" "Sit Down" "Inverted" "Inverted" ...
 $ Drop           : num [1:635] 70 47 110 177 22.5 170 20 147 80 144 ...
 $ Length         : num [1:635] 1050 2963 2956 1204 628 ...
 $ Duration       : num [1:635] 66 140 167 92 47 190 100 143 110 110 ...
 $ Inversions?    : chr [1:635] "Yes" "No" "Yes" "Yes" ...
 $ # of Inversions: num [1:635] 3 0 6 3 0 6 0 0 0 4 ...
 $ Make           : chr [1:635] "Gerstlauer Amusement Rides GmbH" "Arrow Dynamics" "Bolliger &amp; Mabillard" "Vekoma" ...
 $ Latitude       : num [1:635] 45.5 39.4 35.3 47.9 28 ...
 $ Longitude      : num [1:635] -122.7 -84.3 -80.8 -116.7 -82.6 ...
 $ Boundary       : chr [1:635] "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":95988.013,\"NAME\":\"Oregon\",\"GEO_ID\":\"0400000US41\",\"| __truncated__ "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":40860.694,\"NAME\":\"Ohio\",\"GEO_ID\":\"0400000US39\",\"L"| __truncated__ "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":48617.905,\"NAME\":\"North Carolina\",\"GEO_ID\":\"0400000"| __truncated__ "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":82643.117,\"NAME\":\"Idaho\",\"GEO_ID\":\"0400000US16\",\""| __truncated__ ...
 - attr(*, "spec")=
  .. cols(
  ..   Coaster = col_character(),
  ..   Park = col_character(),
  ..   City = col_character(),
  ..   State = col_character(),
  ..   `Census Region` = col_character(),
  ..   `Year Opened` = col_double(),
  ..   AgeGroup = col_character(),
  ..   TopSpeed = col_double(),
  ..   MaxHeight = col_double(),
  ..   Scale = col_character(),
  ..   Type = col_character(),
  ..   Design = col_character(),
  ..   Drop = col_double(),
  ..   Length = col_double(),
  ..   Duration = col_double(),
  ..   `Inversions?` = col_character(),
  ..   `# of Inversions` = col_double(),
  ..   Make = col_character(),
  ..   Latitude = col_double(),
  ..   Longitude = col_double(),
  ..   Boundary = col_character()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p>Looking over the structure, I see that Census Region, AgeGroup, Scale, Type, Design, and Inversions? should be treated as factors.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(raw_coasters<span class="sc">$</span><span class="st">`</span><span class="at">Census Region</span><span class="st">`</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "West"      "Midwest"   "South"     "Northeast"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(raw_coasters<span class="sc">$</span>AgeGroup)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "3:Newest" "2:Recent" "1:Older" </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(raw_coasters<span class="sc">$</span>Scale)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Extreme" "Thrill"  "Family"  "Kiddie" </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(raw_coasters<span class="sc">$</span>Type)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Steel" "Wood" </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(raw_coasters<span class="sc">$</span>Design)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Sit Down"  "Inverted"  "Bobsled"   "Suspended" "Wing"      "Flying"   
[7] "Stand Up" </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(raw_coasters<span class="sc">$</span><span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Yes" "No" </code></pre>
</div>
</div>
<p>Now, to create the factors:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>coasters<span class="ot">&lt;-</span>raw_coasters<span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Latitude,<span class="sc">-</span>Longitude,<span class="sc">-</span>Boundary)<span class="sc">|&gt;</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CensusRegionF=</span><span class="fu">factor</span>(<span class="st">`</span><span class="at">Census Region</span><span class="st">`</span>,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"West"</span>,<span class="st">"Midwest"</span>,<span class="st">"South"</span>,<span class="st">"Northeast"</span>)))<span class="sc">|&gt;</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">AgeGroup=</span><span class="fu">case_match</span>(AgeGroup,<span class="st">"3:Newest"</span><span class="sc">~</span><span class="st">"Newest"</span>,<span class="st">"2:Recent"</span><span class="sc">~</span><span class="st">"Recent"</span>,<span class="st">"1:Older"</span><span class="sc">~</span><span class="st">"Older"</span>))<span class="sc">|&gt;</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">AgeGroupF=</span><span class="fu">factor</span>(AgeGroup,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Newest"</span>,<span class="st">"Recent"</span>,<span class="st">"Older"</span>)))<span class="sc">|&gt;</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ScaleF=</span><span class="fu">factor</span>(Scale,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Extreme"</span>,<span class="st">"Thrill"</span>,<span class="st">"Family"</span>,<span class="st">"Kiddie"</span>)))<span class="sc">|&gt;</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TypeF=</span><span class="fu">factor</span>(Type,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Steel"</span>,<span class="st">"Wood"</span>)))<span class="sc">|&gt;</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DesignF=</span><span class="fu">factor</span>(Design,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Sit Down"</span>,<span class="st">"Inverted"</span>,<span class="st">"Bobsled"</span>,<span class="st">"Suspended"</span>,<span class="st">"Wing"</span>,<span class="st">"Flying"</span>,<span class="st">"Stand Up"</span>)))<span class="sc">|&gt;</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">InversionsF=</span><span class="fu">factor</span>(<span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Yes"</span>,<span class="st">"No"</span>)))<span class="sc">|&gt;</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="st">`</span><span class="at">Census Region</span><span class="st">`</span>,<span class="sc">-</span>AgeGroup,<span class="sc">-</span>Scale,<span class="sc">-</span>Type,<span class="sc">-</span>Design,<span class="sc">-</span><span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `AgeGroup = case_match(...)`.
Caused by warning:
! `case_match()` was deprecated in dplyr 1.2.0.
ℹ Please use `recode_values()` instead.</code></pre>
</div>
</div>
<section id="section-3" class="level2">
<h2 class="anchored" data-anchor-id="section-3">4.</h2>
<p>Now that we have some cleaned up data, we can look at it to verify that everything is looking good:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>coasters</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 635 × 18
   Coaster       Park  City  State `Year Opened` TopSpeed MaxHeight  Drop Length
   &lt;chr&gt;         &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;         &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
 1 Adrenaline P… Oaks… Port… Oreg…          2018     45         72   70     1050
 2 Adventure Ex… King… Mason Ohio           1991     35         63   47     2963
 3 Afterburn     Caro… Char… Nort…          1999     62        113  110     2956
 4 Aftershock    Silv… Athol Idaho          2008     65.6      192. 177     1204
 5 Air Grover    Busc… Tampa Flor…          2010     22         25   22.5    628
 6 Alpengeist    Busc… Will… Virg…          1997     67        195  170     3828
 7 Alpine Bobsl… Grea… Quee… New …          1998     35         64   20     1490
 8 American Eag… Six … Gurn… Illi…          1981     66        127  147     4650
 9 American Thu… Six … Eure… Miss…          2008     48         82   80     2713
10 Anaconda      King… Dosw… Virg…          1991     50        128  144     2700
# ℹ 625 more rows
# ℹ 9 more variables: Duration &lt;dbl&gt;, `# of Inversions` &lt;dbl&gt;, Make &lt;chr&gt;,
#   CensusRegionF &lt;fct&gt;, AgeGroupF &lt;fct&gt;, ScaleF &lt;fct&gt;, TypeF &lt;fct&gt;,
#   DesignF &lt;fct&gt;, InversionsF &lt;fct&gt;</code></pre>
</div>
</div>
<p>All seems pretty reasonable to me.</p>
</section>
<section id="section-4" class="level2">
<h2 class="anchored" data-anchor-id="section-4">5.</h2>
<p>Next, to look for missing variables. For this, I’ll steel the function from the notes.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>sum_na <span class="ot">&lt;-</span> <span class="cf">function</span>(column){</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">is.na</span>(column))</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>na_counts <span class="ot">&lt;-</span> coasters <span class="sc">|&gt;</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), sum_na))<span class="sc">|&gt;</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a> <span class="fu">select</span>(<span class="fu">where</span>(<span class="sc">~</span> .x <span class="sc">&gt;</span> <span class="dv">0</span>))</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>na_counts</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  TopSpeed MaxHeight  Drop Length Duration  Make
     &lt;int&gt;     &lt;int&gt; &lt;int&gt;  &lt;int&gt;    &lt;int&gt; &lt;int&gt;
1       74         8   128     33       66    36</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(na_counts)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 345</code></pre>
</div>
</div>
<p>It looks like there are 6 columns with missing data, good for a total of 345 missing values.</p>
</section>
</section>
<section id="categorical-variables" class="level1">
<h1>Categorical Variables</h1>
<section id="section-5" class="level2">
<h2 class="anchored" data-anchor-id="section-5">6.</h2>
<p>Nest, we’re to create some contingency tables with the factors we created aboce. First, a one-way table:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(coasters<span class="sc">$</span>ScaleF)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Extreme  Thrill  Family  Kiddie 
    269     160     178      28 </code></pre>
</div>
</div>
<p>From the table above, we can see that “Extreme” was the most numerous roller coaster in the data set, with a total of 269 roller coasters being of that type.</p>
<p>And a two-way table:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(coasters<span class="sc">$</span>ScaleF, coasters<span class="sc">$</span>TypeF)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
          Steel Wood
  Extreme   216   53
  Thrill    124   36
  Family    163   15
  Kiddie     27    1</code></pre>
</div>
</div>
<p>Look at the table above, we see that most of the roller coasters are made of steel. In fact, 216 of the 269 Extreme coasters are made of stell.</p>
<p>And three-way:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(coasters<span class="sc">$</span>ScaleF,coasters<span class="sc">$</span>TypeF,coasters<span class="sc">$</span>AgeGroupF)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>, ,  = Newest

         
          Steel Wood
  Extreme   126   21
  Thrill     79   11
  Family    120    5
  Kiddie     14    0

, ,  = Recent

         
          Steel Wood
  Extreme    82   23
  Thrill     27    9
  Family     37    3
  Kiddie      9    0

, ,  = Older

         
          Steel Wood
  Extreme     8    9
  Thrill     18   16
  Family      6    7
  Kiddie      4    1</code></pre>
</div>
</div>
<p>From this table, we can see that the dominance of steel roller coasters is a recent phenomenon. In fact, when we look at the Older category, we see that less than half of the Extreme roller coasters (8 out of 17) were made of steel.</p>
</section>
<section id="section-6" class="level2">
<h2 class="anchored" data-anchor-id="section-6">7.</h2>
<p>Next, we’ll create a two-way table, conditioned on a third variable, in two ways.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>filtered_coasters <span class="ot">&lt;-</span> <span class="fu">filter</span>(coasters, AgeGroupF <span class="sc">==</span> <span class="st">"Older"</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(filtered_coasters<span class="sc">$</span>ScaleF, filtered_coasters<span class="sc">$</span>TypeF)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
          Steel Wood
  Extreme     8    9
  Thrill     18   16
  Family      6    7
  Kiddie      4    1</code></pre>
</div>
</div>
<p>Now, to create the same table another way:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>three_way<span class="ot">&lt;-</span><span class="fu">table</span>(coasters<span class="sc">$</span>ScaleF,coasters<span class="sc">$</span>TypeF,coasters<span class="sc">$</span>AgeGroupF)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>three_way[,,<span class="dv">3</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
          Steel Wood
  Extreme     8    9
  Thrill     18   16
  Family      6    7
  Kiddie      4    1</code></pre>
</div>
</div>
</section>
<section id="section-7" class="level2">
<h2 class="anchored" data-anchor-id="section-7">8.</h2>
<p>Now, we’ll do the same thing with functions in dplr.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>coasters<span class="sc">|&gt;</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ScaleF,TypeF)<span class="sc">|&gt;</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count=</span><span class="fu">n</span>())<span class="sc">|&gt;</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from=</span>TypeF,<span class="at">values_from=</span>count)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   ScaleF [4]
  ScaleF  Steel  Wood
  &lt;fct&gt;   &lt;int&gt; &lt;int&gt;
1 Extreme   216    53
2 Thrill    124    36
3 Family    163    15
4 Kiddie     27     1</code></pre>
</div>
</div>
</section>
<section id="section-8" class="level2">
<h2 class="anchored" data-anchor-id="section-8">9.</h2>
<p>Finally, we’ll create a stacked bar graph and a side-by side bar graph.</p>
<p>First, the stacked bar graph:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coasters, <span class="fu">aes</span>(<span class="at">x =</span> ScaleF, <span class="at">fill =</span> TypeF)) <span class="sc">+</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()<span class="sc">+</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Scale of the roller coaster"</span>,<span class="at">y=</span><span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="st">"Material"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST558_Homework5_Haverhals_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finally, the side-by-side:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coasters, <span class="fu">aes</span>(<span class="at">x =</span> ScaleF, <span class="at">fill =</span> TypeF)) <span class="sc">+</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="st">"dodge"</span>)<span class="sc">+</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Scale of the roller coaster"</span>,<span class="at">y=</span><span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="st">"Material"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST558_Homework5_Haverhals_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>